### ISSUE TITLE
The NICKSERV code doesn't seem correct

### ISSUE THREAD

**Issue by samw15** [weannounce/arrnounced#15]
It looks like the code in irc.py tries to authenticate with the command "NICKSERV".    I believe it should be a PRIVMSG, like:

```
            logger.info("Identifying with NICKSERV")
            await self.rawmsg(
                "PRIVMSG", "NICKSERV", "IDENTIFY" , self.tracker_config.irc_ident_password
            )
```

(sorry for not doing a proper PR, I was just looking at the code)

**Comment by weannounce** [comment]
Yeah, that seems correct. Weird, because the identification has been working. Maybe the servers are lenient in that aspect? I pushed the update here [a8644b39ff59fd285fdebe8f81d2feeeec6b26c8](https://github.com/weannounce/arrnounced/commit/a8644b39ff59fd285fdebe8f81d2feeeec6b26c8)

Always good with another set of eyes on things. Thanks

**Comment by samw15** [comment]
I later noticed that some servers seem to have NICKSERV as some kind of alias/wrapper.  Perhaps a "native" command is considered more secure than a PRIVMSG.
