### ISSUE TITLE
Tracker seems to require cookies to download torrent file issue

### ISSUE THREAD

**Issue by merger3** [weannounce/arrnounced#21]
Some trackers I have added are telling me "Tracker seems to require cookies to download torrent file. Sonarr/Radarr/Lidarr API does not support cookies."

Does this mean they're not going to be usable with this program for automatic downloading or is there a workaround?

**Comment by weannounce** [comment]
The API that, for example, Sonarr offers to push releases can be found here https://github.com/Sonarr/Sonarr/wiki/Release-Push. Since there is not field to pass cookies to Sonarr there is no way to set the cookie when it downloads the torrent file.

With that said, it depends on the tracker if the cookie is required to download the file. If it is required, there is no workaround for it that I can think of. Sonarr et. al. needs to extend the API to allow cookies.

Check what the requirements for the tracker is or you can simply try to fetch the file manually to see if you succeed (just remember to do it in a browser without any cookies set).
